version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8001"
    depends_on:
      - db
      - rabbitmq
    environment:
      - DATABASE_URL=postgresql://postgres:root@db/produits
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq/
    networks:
      - shared-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: produits
    ports:
      - "5435:5432"
    networks:
      - shared-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15673"
    networks:
      - shared-network

networks:
  shared-network:
    external: true
