name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker images
      run: docker-compose build

    - name: Start services
      run: docker-compose up

    - name: Wait for services to be ready
      run: |
        sleep 10
        docker ps

    - name: Run tests
      run: |
        docker-compose exec web python -m unittest discover

    - name: Stop services
      run: docker-compose down
